/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package risc;

import risc.interfaces.server.GameServer;
import risc.server.GameServerV1;

import java.util.Scanner;

public class App {

  public static void main(String[] args) throws Exception {

    Scanner scanner = new Scanner(System.in);
    String line = "N";
    while (true) {
      while (true) {
        System.out.println("(N)ew Game or (E)nd?");
        line = scanner.nextLine();
        if (line.equals("E")) {
          return;
        } else if (line.equals("N")) {
          break;
        }
      }
      int numPlayer = 2;
      while (true) {
        System.out.println("Please enter number of player (less than or equal to 5): ");
        line = scanner.nextLine();
        try {
          numPlayer = Integer.valueOf(line);
          if (numPlayer <= 5 && numPlayer > 0) {
            break;
          }
        } catch (Exception ignored) {
        }
      }
      GameServer gameServer = new GameServerV1(8080, numPlayer);
      gameServer.run();
    }

  }
}

